bin: git
style: github
template: CHANGELOG.tpl.md

info:
  title: CHANGELOG
  repository_url: https://github.com/lwijshoff/waldjugend-theme

options:
  tag_filter_pattern: '^v'
  sort: date

  commits:
    # Include regular commits and PR merges that have a type prefix
    filters:
      Type:
        - feat
        - fix
        - refactor
        - perf
    sort_by: Scope

  commit_groups:
    group_by: Type
    sort_by: Title
    title_order:
      - feat
      - fix
      - refactor
      - perf
    title_maps:
      feat: New Features
      fix: Bug Fixes
      refactor: Code Refactoring
      perf: Performance Improvements

  header:
    # parse type: subject from commit message, including PR merges if they have type
    pattern: "^(\\w*):\\s(.*)$"
    pattern_maps:
      - Type
      - Subject

  issues:
    prefix:
      - "#"

  refs:
    actions:
      - Closes
      - Fixes

  merges:
    # Only treat merges without a type prefix as special merges
    pattern: "^Merge pull request #\\d+ from (?!feat|fix|refactor|perf).*"
    pattern_maps:
      - Source

  reverts:
    pattern: "^Revert \"([\\s\\S]*)\"$"
    pattern_maps:
      - Header

  notes:
    keywords:
      - BREAKING CHANGE