name: Release Theme

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare and zip
        run: |
          mkdir dist
          mv $GITHUB_WORKSPACE dist/waldjugend-theme
          cd dist
          zip -r waldjugend-theme.zip waldjugend-theme -x "*.git*"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/waldjugend-theme.zip