name: Package Theme

on:
  release:
    types: [created]

jobs:
  build-zip:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Prepare package folder
      - name: Prepare package folder
        run: |
          PACKAGE_DIR=waldjugend-theme
          ZIP_NAME="waldjugend-theme-${GITHUB_REF##*/}.zip"

          # Remove any old temp folder or ZIP
          rm -rf $PACKAGE_DIR $ZIP_NAME

          # Create temp folder
          mkdir $PACKAGE_DIR

          # Copy all project files into the temp folder while excluding unwanted files
          rsync -av --progress ./ "$PACKAGE_DIR" \
            --exclude='.git*' \
            --exclude='.github/*' \
            --exclude='.chglog/*' \
            --exclude='tests/*' \
            --exclude="$PACKAGE_DIR"

      # Create ZIP archive
      - name: Create ZIP
        run: |
          ZIP_NAME="waldjugend-theme-${GITHUB_REF##*/}.zip"
          zip -r "$ZIP_NAME" waldjugend-theme

      # Upload ZIP as release asset
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: "waldjugend-theme-${GITHUB_REF##*/}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}