name: Package Theme

on:
  release:
    types: [published]

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up release version and zip name
        id: vars
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          ZIPNAME="waldjugend-theme-${TAG}.zip"
          echo "ZIPNAME=$ZIPNAME" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Prepare theme directory
        run: |
          mkdir -p waldjugend-theme
          rsync -av --exclude='.git*' --exclude='.github' ./ waldjugend-theme/
          ls -la waldjugend-theme

      - name: Create the zip file
        run: |
          zip -r "$ZIPNAME" waldjugend-theme

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIPNAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}